version: "3"
services: 
  starstuff:
    image: starstuff
    restart: unless-stopped
    stdin_open: true
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - mern-app
    volumes: 
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  api:
    image: api
    restart: unless-stopped
    build: ./api/
    ports: 
      - "4000:4000"
    networks: 
      - mern-app
    depends_on: 
      - mongo
    volumes: 
    - ./api/:/usr/src/app
    - /usr/src/app/node_modules

  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local